using System.Globalization;
using Microsoft.Data.Sqlite;

namespace MoatHouseHandover.Host.Sqlite.Repositories;

public sealed class SqlitePreviewRepository : SqliteRepositoryBase, IPreviewRepository
{
    public SqlitePreviewRepository(string sqlitePath, string dataRoot) : base(sqlitePath, dataRoot) { }

    public PreviewPayload LoadPreview(long sessionId)
    {
        using var c = OpenConnection();
        var header = LoadHeader(c, sessionId) ?? throw new InvalidOperationException($"Session '{sessionId}' was not found.");
        var departments = LoadDepartments(c, sessionId);
        var attachmentSummary = LoadAttachmentSummary(c, sessionId);
        var budgetRows = LoadBudgetRows(c, sessionId);
        var budgetSummary = BuildBudgetSummary(budgetRows);
        return new PreviewPayload(header, departments, attachmentSummary, budgetSummary, budgetRows);
    }

    private static PreviewSessionHeader? LoadHeader(SqliteConnection c, long sid){ using var cmd=c.CreateCommand(); cmd.CommandText="SELECT HandoverID, ShiftCode, ShiftDate, SessionStatus, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy FROM tblHandoverHeader WHERE HandoverID=$id LIMIT 1"; cmd.Parameters.AddWithValue("$id", sid); using var r=cmd.ExecuteReader(); if(!r.Read()) return null; return new PreviewSessionHeader(r.GetInt64(0), r.IsDBNull(1)?string.Empty:r.GetString(1), r.IsDBNull(2)?string.Empty:r.GetString(2), r.IsDBNull(3)?"Open":r.GetString(3), r.IsDBNull(4)?null:r.GetString(4), r.IsDBNull(5)?string.Empty:r.GetString(5), r.IsDBNull(6)?null:r.GetString(6), r.IsDBNull(7)?string.Empty:r.GetString(7)); }
    private static List<PreviewDepartmentSummary> LoadDepartments(SqliteConnection c, long sid){ var departments=new List<PreviewDepartmentSummary>(); using var cmd=c.CreateCommand(); cmd.CommandText=@"SELECT d.DeptRecordID, d.DeptName, d.DeptStatus, d.DowntimeMin, d.EfficiencyPct, d.YieldPct, d.DeptNotes, d.UpdatedAt, d.UpdatedBy, SUM(CASE WHEN a.AttachmentID IS NOT NULL AND COALESCE(a.IsDeleted,0)=0 THEN 1 ELSE 0 END) AS AttachmentCount, cfg.DisplayOrder FROM tblHandoverDept d LEFT JOIN tblDepartments cfg ON cfg.DeptName=d.DeptName LEFT JOIN tblAttachments a ON a.DeptRecordID=d.DeptRecordID WHERE d.HandoverID=$sid AND COALESCE(d.IsDeleted,0)=0 GROUP BY d.DeptRecordID,d.DeptName,d.DeptStatus,d.DowntimeMin,d.EfficiencyPct,d.YieldPct,d.DeptNotes,d.UpdatedAt,d.UpdatedBy,cfg.DisplayOrder ORDER BY cfg.DisplayOrder, d.DeptName"; cmd.Parameters.AddWithValue("$sid", sid); using var r=cmd.ExecuteReader(); while(r.Read()) departments.Add(new PreviewDepartmentSummary(r.GetInt64(0),r.IsDBNull(1)?"":r.GetString(1),r.IsDBNull(2)?"Not running":r.GetString(2),r.IsDBNull(3)?null:r.GetInt32(3),r.IsDBNull(4)?null:r.GetDouble(4),r.IsDBNull(5)?null:r.GetDouble(5),r.IsDBNull(6)?"":r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.IsDBNull(8)?null:r.GetString(8),r.IsDBNull(9)?0:r.GetInt32(9))); return departments; }
    private static List<PreviewAttachmentDepartmentSummary> LoadAttachmentSummary(SqliteConnection c,long sid){ var grouped=new Dictionary<string,List<PreviewAttachmentMeta>>(StringComparer.OrdinalIgnoreCase); using var cmd=c.CreateCommand(); cmd.CommandText="SELECT DeptName, AttachmentID, DisplayName, CapturedOn, SequenceNo FROM tblAttachments WHERE HandoverID=$sid AND COALESCE(IsDeleted,0)=0 ORDER BY DeptName, SequenceNo, AttachmentID"; cmd.Parameters.AddWithValue("$sid",sid); using var r=cmd.ExecuteReader(); while(r.Read()){ var dept=r.IsDBNull(0)?string.Empty:r.GetString(0); if(!grouped.TryGetValue(dept,out var list)){ list=[]; grouped[dept]=list;} list.Add(new PreviewAttachmentMeta(r.GetInt64(1),r.IsDBNull(2)?"":r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.IsDBNull(4)?0:r.GetInt64(4))); } return grouped.OrderBy(p=>p.Key,StringComparer.OrdinalIgnoreCase).Select(p=>new PreviewAttachmentDepartmentSummary(p.Key,p.Value.Count,p.Value)).ToList(); }
    private static List<PreviewBudgetRowSummary> LoadBudgetRows(SqliteConnection c,long sid){ var rows=new List<PreviewBudgetRowSummary>(); using var cmd=c.CreateCommand(); cmd.CommandText=@"SELECT r.DeptName, r.PlannedQty, r.UsedQty, r.VarianceQty, r.ReasonText, r.UpdatedAt, r.UpdatedBy, d.DisplayOrder FROM tblBudgetRows r INNER JOIN tblBudgetHeader h ON h.BudgetHeaderID=r.BudgetHeaderID LEFT JOIN tblDepartments d ON d.DeptName=r.DeptName WHERE h.HandoverID=$sid ORDER BY d.DisplayOrder, r.DeptName, r.BudgetRowID"; cmd.Parameters.AddWithValue("$sid",sid); using var rd=cmd.ExecuteReader(); while(rd.Read()){ double? p=rd.IsDBNull(1)?null:rd.GetDouble(1); double? u=rd.IsDBNull(2)?null:rd.GetDouble(2); var v=rd.IsDBNull(3)?(p??0)-(u??0):rd.GetDouble(3); rows.Add(new PreviewBudgetRowSummary(rd.IsDBNull(0)?"":rd.GetString(0),p,u,v,ResolveBudgetStatus(p,u,v),rd.IsDBNull(4)?"":rd.GetString(4),rd.IsDBNull(5)?null:rd.GetString(5),rd.IsDBNull(6)?null:rd.GetString(6))); } return rows; }
    private static PreviewBudgetSummary BuildBudgetSummary(IReadOnlyList<PreviewBudgetRowSummary> rows){ var p=rows.Sum(r=>r.PlannedQty??0); var u=rows.Sum(r=>r.UsedQty??0); var v=p-u; var status=ResolveBudgetStatus(p,u,v); var last=rows.Where(r=>!string.IsNullOrWhiteSpace(r.UpdatedAt)).OrderByDescending(r=>r.UpdatedAt,StringComparer.Ordinal).FirstOrDefault(); return new PreviewBudgetSummary(p,u,v,status,last?.UpdatedAt,last?.UpdatedBy,rows.Count); }
    private static string ResolveBudgetStatus(double? planned, double? used, double variance){ var p=planned??0; var u=used??0; if(Math.Abs(p)<0.0001 && Math.Abs(u)<0.0001) return "not set"; if(Math.Abs(variance)<0.0001) return "on target"; return variance<0?"over":"under"; }
}
